### ISSUE TITLE
How to allow an /assets folder within /src be accessible from scss?

### ISSUE THREAD

**Issue by simonghales** [Torwori/ts-mobx-react-starter-kit#2]
Hey there, thanks for this kit, it's been quite handy!

I'm trying to reference a background image from my scss files.

I.e
```
.image {
background-image: url(/assets/image.jpg);
}
```

Where the files is located at `/src/assets/image.jpg`

However when inspecting this element and checking out the path `localhost:8080/assets/image.jpg` there's no image found.

I'd encountered this issue on similar React projects, but I'm having trouble working out how to get it all working here.

Any advice would be greatly appreciated.

Cheers!

**Comment by simonghales** [comment]
Scratch that, I found a simple solution using this plugin:

https://github.com/kevlened/copy-webpack-plugin

and using this code:

`new CopyWebpackPlugin([ { from: 'src/assets', to: 'assets' } ])`

**Comment by Torwori** [comment]
Hi,

The Copy plugin is one way to do it. You could also setup url/file loader
for jpg and use a relative path.

So, instead of `/assets/image.jpg`, you'll have `../assets/image.jpg` and
webpack will do its magic.

Glad you found the kit useful. :smile:
